version: "3.9"

services:
  chatserver:
    image: chatserver:1
    ports:
      - "4000:4000"
      - "8080:8080"
    networks:
      - chatapp
    depends_on:
      - postgres

  chatclient:
    image: chatclient:1
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - chatapp

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "chatapppassword"
    networks:
      - chatapp

networks:
  chatapp:
    driver: bridge
